{% set name = "xlsx2csv" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xlsx2csv-{{ version }}.tar.gz
  sha256: 6c65d5989e8d3f14dd7296d425d693a67f51899d0c8e1ed7bcbf9ccb18223734

build:
  entry_points:
    - xlsx2csv = xlsx2csv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - setuptools >=61.2.0
    - wheel
    - setuptools-scm >=3.4.3
    - pip
  run:
    - python >=3.4

test:
  imports:
    - xlsx2csv
  commands:
    - pip check
    - xlsx2csv --help
  requires:
    - pip

about:
  home: https://github.com/dilshod/xlsx2csv
  summary: xlsx to csv converter
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - borchero
